fix(s3): update actions MTA-2434
scaleway/docs-content pull request #1050
Opened 2022-11-30 15:33 UTC by ldecarvalho-doc

2022-11-30 16:55 UTC, RoRoJ approved these changes

2022-11-30 17:41 UTC, lvjp requested changes

2022-11-30 17:41 UTC, lvjp commented on storage/object/api-cli/using-api-call-list.mdx
> +|  [CreateBucket](/storage/object/api-cli/bucket-operations/#putbucket) |  Creates bucket | ✅ |
Maybe, we also can change naming `PutBucket` -> `CreateBucket` in this page : /storage/object/api-cli/bucket-operations/#putbucket

2022-12-01 13:26 UTC, bene2k1 approved these changes

2022-12-01 14:12 UTC, qselle commented
GetBucket should be renamed to ListObjects and ListObjectsV2 should be added.

2022-12-01 15:58 UTC, lvjp approved these changes

2022-12-01 16:02 UTC, qselle commented
LGTM :+1:

2022-12-01 16:53 UTC, merged