docs(tutorial): add k8s fluentbit observability tutorial
scaleway/docs-content pull request #1680
Opened 2023-05-20 07:56 UTC by antoinechampion

### Your checklist for this pull request

- [X] Check that the commit messages match our requested structure.
- [X] Name your pull request according to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md).

### Description
Tutorial for using Github Actions along with Scaleway Container Registry. See https://github.com/scaleway/docs-content/issues/1517.

2023-05-23 08:01 UTC, RoRoJ reviewed
Thanks for your tutorial :-) I have left some comments, mostly because we prefer to use numbered steps where possible (one step = one action, and should start with an action verb).

2023-05-23 08:01 UTC, RoRoJ commented on tutorials/k8s-fluentbit-observability/index.mdx
> +4. After clicking **Load** you can access the new dashboard named **Node Exporter Server Metrics**.
```suggestion
4. Click **Load** to access the new dashboard named **Node Exporter Server Metrics**.
```

2023-05-23 08:01 UTC, RoRoJ commented on tutorials/k8s-fluentbit-observability/index.mdx
> +2. Click on **New**, **Folder** and name it `Kapsule`
```suggestion
2. Click **New**, **Folder** and name it `Kapsule`
```

2023-05-23 08:01 UTC, RoRoJ commented on tutorials/k8s-fluentbit-observability/index.mdx
> +3. Click on **New**, **Import** and paste the following URL in the **Import via grafana.com** field:
```suggestion
3. Click **New**, **Import** and paste the following URL in the **Import via grafana.com** field:
```

2023-05-30 13:40 UTC, nerda-codes commented on tutorials/k8s-fluentbit-observability/index.mdx
> +In the `values.yaml` file, create a section named `config.outputs`:
```suggestion
2. Create a section named `config.outputs` in the `values.yaml` file:
```

2023-05-30 13:40 UTC, nerda-codes commented on tutorials/k8s-fluentbit-observability/index.mdx
> +In the same directory as your `values.yaml` file, run:
```suggestion
Run the following command in the same directory as your `values.yaml` file:
```

2023-05-30 16:07 UTC, blazarecki-scaleway requested changes

2023-05-30 16:07 UTC, blazarecki-scaleway commented on tutorials/k8s-fluentbit-observability/index.mdx
> +        Scrape_interval       2
Can you update the scrape_interval to be `60s` ? 
A `2s` scrape interval will increase the cost a lot on Cockpit.
Having it to `60s` divide the price by 30.

2023-05-30 16:07 UTC, blazarecki-scaleway commented on tutorials/k8s-fluentbit-observability/index.mdx
> +    https://grafana.com/grafana/dashboards/405-node-exporter-server-metrics/
I think this dashboard `https://grafana.com/grafana/dashboards/1860-node-exporter-full/` is better, what do you think ? The one you provided is from 2018 and this one is up to date. (And nicer but it's a matter of taste)

2023-06-01 15:10 UTC, nerda-codes commented on tutorials/k8s-fluentbit-observability/index.mdx
> +        Scrape_interval       2
```suggestion
        Scrape_interval       60
```

2023-06-01 15:10 UTC, nerda-codes commented on tutorials/k8s-fluentbit-observability/index.mdx
> +    https://grafana.com/grafana/dashboards/405-node-exporter-server-metrics/
```suggestion
    https://grafana.com/grafana/dashboards/1860-node-exporter-full/
```

2023-06-01 15:10 UTC, nerda-codes commented on tutorials/k8s-fluentbit-observability/index.mdx
> +helm upgrade --install fluent-bit fluent/fluent-bit -f .\values.yaml
```suggestion
helm upgrade --install fluent-bit fluent/fluent-bit -f ./values.yaml
```

2023-06-01 15:11 UTC, nerda-codes approved these changes

2023-06-01 15:22 UTC, RoRoJ approved these changes

2023-06-01 15:22 UTC, merged

2023-06-03 06:50 UTC, antoinechampion commented
Apologies for the late reply I was away for a bit. Thank you for taking care of the fit and finish!