docs(ipfs): review api/cli section MTA-3423
scaleway/docs-content pull request #1961
Opened 2023-07-20 16:19 UTC by farhakennar

2023-07-21 12:02 UTC, bene2k1 approved these changes

2023-07-21 13:38 UTC, jcirinosclwy approved these changes

2023-07-31 22:42 UTC, OnsagerHe requested changes

2023-07-31 22:42 UTC, OnsagerHe commented on labs/ipfs/api-cli/pin-operations.mdx
> +      "volume_id": "6170692e-7363-616c-6577-61792e636f6d"
replace volume uuid by example value: 11111111-1111-1111-1111-111111111111

2023-07-31 22:42 UTC, OnsagerHe commented on labs/ipfs/api-cli/pin-operations.mdx
> +This operation allows you to delete a given pin within a volume using its pin ID. If you were the last owner of the associated content, the content will be permanently deleted.
`If you were the last owner of the associated content` this sentence can be deleted as it explains an implementation detail that is not important.

2023-08-01 08:04 UTC, bene2k1 commented on labs/ipfs/api-cli/pin-operations.mdx
> +      "volume_id": "6170692e-7363-616c-6577-61792e636f6d"
```suggestion
      "volume_id": "11111111-1111-1111-1111-111111111111"
```

2023-08-01 08:04 UTC, bene2k1 commented on labs/ipfs/api-cli/pin-operations.mdx
> +This operation allows you to delete a given pin within a volume using its pin ID. If you were the last owner of the associated content, the content will be permanently deleted.
```suggestion
This operation allows you to delete a given pin within a volume using its pin ID.
```

2023-08-01 08:37 UTC, merged