fix(tutorial): correct proxy protol tuto
scaleway/docs-content pull request #2843
Opened 2024-03-05 17:06 UTC by RoRoJ

Correct and improve proxy protocol tutorial after user feedback

2024-03-06 08:42 UTC, RoRoJ commented on tutorials/proxy-protocol-v2-load-balancer/index.mdx
>        Once ProxyProtocol is enabled the Nginx virtual host will no longer accept direct connections.
```suggestion
      Once Proxy Protocol is enabled the Nginx virtual host will no longer accept direct connections. See the [NGINX Proxy Protocol documentation](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/) for full details.
```

2024-03-06 09:08 UTC, clebigot requested changes

2024-03-06 09:08 UTC, clebigot commented on tutorials/proxy-protocol-v2-load-balancer/index.mdx
>        }
There are two more spaces than needed, closing brace should be aligned with the `h` from `http` on line 131

2024-03-06 16:23 UTC, RoRoJ commented on tutorials/proxy-protocol-v2-load-balancer/index.mdx
> +  - You have [configured your SSH key](/console/project/how-to/create-ssh-key)
Well spotted, thanks!

2024-03-06 17:01 UTC, clebigot approved these changes

2024-03-07 10:00 UTC, bene2k1 approved these changes

2024-03-07 13:14 UTC, merged