docs(ifr): add data processing information
scaleway/docs-content pull request #3190
Opened 2024-05-20 09:35 UTC by bene2k1

### Your checklist for this pull request

- [ ] Name your pull request according to the [contribution guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md).

### Description

Please describe what you added or changed.

2024-05-28 12:22 UTC, bene2k1 commented
do not merge before validated by legal team

2024-06-03 08:42 UTC, tgenaitay commented
Message de la légal team

> Nous n'avons pas de compte Github au service legal pour valider la policy, je valide donc via ce ticket la politique privacy destinée à la documentation.

2024-06-03 12:22 UTC, seiteta requested changes

2024-06-03 14:33 UTC, bene2k1 commented on ai-data/managed-inference/reference-content/data-privacy-security-scaleway-ai-services.mdx
> +
@seiteta do you mean the whole part "Data processing" or just the information about Input Data / Metadata ?

2024-06-04 13:15 UTC, seiteta commented on ai-data/managed-inference/reference-content/data-privacy-security-scaleway-ai-services.mdx
> +
@bene2k1: please find my suggestion in my [commit ](https://github.com/scaleway/docs-content/pull/3190/commits/10c85daaa81acb82653b40985d2bdd30ca741bf1)

2024-06-04 14:56 UTC, bene2k1 commented
@tgenaitay we can merge this if good for you.

2024-06-04 15:00 UTC, ldecarvalho-doc approved these changes

2024-06-04 15:08 UTC, nerda-codes approved these changes

2024-06-04 15:08 UTC, nerda-codes commented on ai-data/managed-inference/reference-content/data-privacy-security-scaleway-ai-services.mdx
> +Scaleway's AI services implement robust security measures to ensure customer data privacy and integrity. Below is an overview of these practices:
```suggestion
Scaleway's AI services implement robust security measures to ensure customer data privacy and integrity. Below is an overview of these practices.
```

2024-06-05 05:46 UTC, tgenaitay commented
Well done! 

Was wondering if it’s worth putting some words about our compliance with RGPD and how our AI services not obliged by extra territorial laws such as the American Cloud Act.
My feeling is that our EU customers see it as advantage for Scaleway overall, but whoever reads this page in the future (data teams new to Scaleway) could use a clear statement in the context of AI. 

https://fr.linkedin.com/pulse/app-et-infrastructure-quelle-souverainet%C3%A9-mieux-pour-choisir-morales-0upde

2024-06-06 13:28 UTC, seiteta approved these changes

2024-06-07 12:29 UTC, tgenaitay commented
Perfect to start with! Many thanks.

2024-06-07 12:30 UTC, tgenaitay approved these changes

2024-06-07 12:31 UTC, merged