docs(tuto): add meilisearch tuto
scaleway/docs-content pull request #3520
Opened 2024-07-24 15:43 UTC by nerda-codes

2024-07-24 15:52 UTC, fpagny requested changes

2024-07-24 15:52 UTC, fpagny commented on tutorials/deploy-meilisearch-instance/index.mdx
> +    {"commitSha":"0df84bbba7db46680e83843dd6454257161a282f","commitDate":"2024-06-27T12:47root@scwrororororrrrrrrrrrrrrrrrorrrorrrrrrrrrrrrroot@scw-lucid-satoshi:~#
This line feels like there is a copy paste issue.
The format should be json only, like {"commitSha":"0df84bbba7db46680e83843dd6454257161a282f","commitDate":"2024-06-27T12", "pkgVersion":aaaaaa}

2024-07-24 15:53 UTC, nerda-codes commented on tutorials/deploy-meilisearch-instance/index.mdx
> +    {"commitSha":"0df84bbba7db46680e83843dd6454257161a282f","commitDate":"2024-06-27T12:47root@scwrororororrrrrrrrrrrrrrrrorrrorrrrrrrrrrrrroot@scw-lucid-satoshi:~#
```suggestion
    {"commitSha":"0df84bbba7db46680e83843dd6454257161a282f","commitDate":"2024-06-27T12", "pkgVersion":aaaaaa}
```

2024-07-24 15:54 UTC, fpagny approved these changes

2024-07-25 06:51 UTC, RoRoJ commented on tutorials/deploy-meilisearch-instance/index.mdx
> +     If you are using an Instance with a Docker InstantApp, run `docker -v` to make sure that the Docker engine is already installed. The current docker engine version should display.
```suggestion
     If you are using an Instance with a Docker InstantApp, run `docker -v` to make sure that the Docker engine is already installed. The current Docker engine version should display.
```

2024-07-25 06:53 UTC, RoRoJ commented on tutorials/deploy-meilisearch-instance/index.mdx
> +- **Fine-tune deployment configuration** such as [Instances or disk size](/compute/instances/reference-content/choosing-instance-type/), from the [Scaleway console](https://console.scaleway.com/insta
```suggestion
- **Fine-tune deployment configuration** such as [Instance type or disk size](/compute/instances/reference-content/choosing-instance-type/), from the [Scaleway console](https://console.scaleway.com/instance/servers), [the Scaleway API](https://www.scaleway.com/en/developers/api/instance/), [CLI](/compute/instances/api-cli/cli-cheatsheet/) or [Terraform](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/instance_server).
```

2024-07-25 06:53 UTC, RoRoJ commented on tutorials/deploy-meilisearch-instance/index.mdx
> +If you encounter any issues, check that you meet all the [requirements listed at the beginning of this page](#before-you-start). Also, verify that your Instance accepts connections from your computer
```suggestion
If you encounter any issues, check that you meet all the [requirements listed at the beginning of this page](#before-you-start). Also, verify that your Instance accepts connections from your computer. To do so, you can configure [security groups](/compute/instances/how-to/use-security-groups/) or a [Public Gateway](/network/public-gateways/how-to/configure-a-public-gateway/) on the [Private Network](/compute/instances/how-to/use-private-networks/) your Instance belongs to.
```

2024-07-25 09:51 UTC, bene2k1 approved these changes

2024-07-25 09:51 UTC, bene2k1 commented on tutorials/deploy-meilisearch-instance/index.mdx
> +[Meilisearch](https://www.meilisearch.com/) is an open-source search engine that provides instant and relevant search results from large collections of data. Meilisearch is particularly useful for ap
```suggestion
Meilisearch is an open-source search engine that provides instant and relevant search results from large collections of data. Meilisearch is particularly useful for applications that require fast and efficient search capabilities, such as e-commerce sites, documentation search, and any platform where users need to quickly find relevant information from a large dataset.
```

removed first link for seo

2024-07-25 09:51 UTC, bene2k1 commented on tutorials/deploy-meilisearch-instance/index.mdx
> +
```suggestion
```

2024-07-25 12:26 UTC, RoRoJ approved these changes

2024-07-25 12:27 UTC, nerda-codes commented on tutorials/deploy-meilisearch-instance/index.mdx
> +- A Scaleway account logged into the [console](https://console.scaleway.com)
```suggestion
- A Scaleway account logged into the [console](https://console.scaleway.com/)
```

2024-07-25 12:40 UTC, merged