docs(tem): webhook events payload
scaleway/docs-content pull request #3734
Opened 2024-09-20 13:17 UTC by ldecarvalho-doc

2024-09-20 15:28 UTC, bene2k1 approved these changes

2024-09-23 09:33 UTC, jcirinosclwy commented on managed-services/transactional-email/api-cli/webhook-events-payload.mdx
> +tags: spf spf-record dkim dkim-records dmarc dmarc-record transactional
```suggestion
tags: spf dkim dmarc transactional
```

2024-09-23 09:34 UTC, jcirinosclwy approved these changes

2024-09-23 12:16 UTC, jerjako commented on managed-services/transactional-email/api-cli/webhook-events-payload.mdx
> +    "created_at": string,
```suggestion
    "created_at": date,
```

2024-09-23 12:16 UTC, jerjako commented on managed-services/transactional-email/api-cli/webhook-events-payload.mdx
> +	"email_headers": [{"name": string, "value": string}],
We should put the slice or array in multiple lines, or the github view messed up with the colors

Like this:
```suggestion
	"email_headers": [{
		"name": string,
		"value": string
	}],
```

2024-09-23 12:16 UTC, jerjako commented on managed-services/transactional-email/api-cli/webhook-events-payload.mdx
> +    "created_at": string,
```suggestion
    "created_at": date,
```

2024-09-23 12:27 UTC, moutoum requested changes
For date types, I'd suggest to had the date format: `RFC3339`

2024-09-23 12:27 UTC, moutoum commented on managed-services/transactional-email/api-cli/webhook-events-payload.mdx
> +| `email_queued_at` | Email reception date in by TEM proxy or API                                                          |
```suggestion
| `email_queued_at` | Email reception date by TEM proxy or API                                                          |
```

2024-09-23 12:27 UTC, moutoum commented on managed-services/transactional-email/api-cli/webhook-events-payload.mdx
> +| `email_next_try`   | Next time we will try to send the email to the recipient server  |
```suggestion
| `email_next_try`   | Next time the email will be sent to the recipient server  |
```

2024-09-23 12:41 UTC, nerda-codes approved these changes

2024-09-23 13:10 UTC, jerjako approved these changes

2024-09-23 13:10 UTC, jerjako commented on managed-services/transactional-email/api-cli/webhook-events-payloads.mdx
> +  "created_at": string,
```suggestion
  "created_at": date,
```

2024-09-23 13:10 UTC, jerjako commented on managed-services/transactional-email/api-cli/webhook-events-payloads.mdx
> +  "created_at": string,
```suggestion
  "created_at": date,
```

2024-09-23 13:10 UTC, jerjako commented on managed-services/transactional-email/api-cli/webhook-events-payloads.mdx
> +  "created_at": string,
```suggestion
  "created_at": date,
```

2024-09-23 13:10 UTC, jerjako commented on managed-services/transactional-email/api-cli/webhook-events-payloads.mdx
> +  "created_at": string,
```suggestion
  "created_at": date,
```

2024-09-23 15:19 UTC, merged