feat(redis): allowed ips MTA-2004c
scaleway/docs-content pull request #721
Opened 2022-07-12 12:37 UTC by ldecarvalho-doc

### Your checklist for this pull request

- [ ] Check that the commit messages match our requested structure.
- [ ] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).

### Description
Please describe your pull request.

2022-07-12 13:39 UTC, bene2k1 approved these changes

2022-07-13 08:07 UTC, nzerhouni requested changes

2022-07-13 08:07 UTC, nzerhouni commented on databases/databases-for-redis/how-to/create-a-database-for-redis.mdx
>  6. Click **Create Database for Redis™** to confirm your choices and launch creation.
```suggestion
6. Click **Create a Redis™ Database Instance** to confirm your choices and launch creation.
```

2022-07-13 08:07 UTC, nzerhouni commented on databases/databases-for-redis/how-to/manage-allowed-ip-addresses-redis.mdx
> +1. Click **Databases Redis™** under **Database** on the side menu. A list of your Database Instances displays.
```suggestion
1. Click **Databases Redis™** under **Databases** on the side menu. A list of your Database Instances displays.
```

2022-07-13 08:07 UTC, nzerhouni commented on databases/databases-for-redis/how-to/manage-allowed-ip-addresses-redis.mdx
> +- You have a [Database for Redis™](/databases/databases-for-redis/how-to/create-a-database-for-redis)
```suggestion
- You have a [Redis™ Database Instance](/databases/databases-for-redis/how-to/create-a-database-for-redis)
```

2022-07-13 08:07 UTC, nzerhouni commented on databases/databases-for-redis/how-to/manage-allowed-ip-addresses-redis.mdx
> +  <PreviousButton to="/databases/databases-for-redis/how-to/create-a-database-for-redis">How to create a Database for Redis™</PreviousButton>
```suggestion
  <PreviousButton to="/databases/databases-for-redis/how-to/create-a-database-for-redis">How to create a Redis™ Database Instance</PreviousButton>
```

2022-07-13 08:07 UTC, nzerhouni commented on databases/databases-for-redis/how-to/scale-up-a-database-for-redis.mdx
>    <NextButton to="/databases/databases-for-redis/how-to/delete-a-database-for-redis">How to delete a Database for Redis™</NextButton>
```suggestion
  <NextButton to="/databases/databases-for-redis/how-to/delete-a-database-for-redis">How to delete a Redis™ Database Instance</NextButton>
```

2022-07-13 09:47 UTC, ldecarvalho-doc commented
errata

2022-07-13 09:47 UTC, closed without merging