feat(redis): advanced settings
scaleway/docs-content pull request #727
Opened 2022-07-20 12:30 UTC by ldecarvalho-doc

2022-07-20 13:22 UTC, nedaehm approved these changes

2022-07-21 08:23 UTC, nzerhouni requested changes

2022-07-21 08:23 UTC, nzerhouni commented on databases/databases-for-redis/how-to/configure-advanced-settings-redis.mdx
> +  description: This page explains how to configure advanced Database for Redis™ settings
```suggestion
  description: This page explains how to configure advanced Databases for Redis™ settings 
```

2022-07-21 08:23 UTC, nzerhouni commented on databases/databases-for-redis/how-to/configure-advanced-settings-redis.mdx
> +  paragraph: This page explains how to configure advanced Database for Redis™ settings
```suggestion
  paragraph: This page explains how to configure advanced Databases for Redis™ settings 
```

2022-07-25 11:59 UTC, bene2k1 approved these changes

2022-07-25 11:59 UTC, RoRoJ approved these changes

2022-07-25 14:30 UTC, merged