fix(redis): new naming MTA-2106
scaleway/docs-content pull request #747
Opened 2022-07-29 13:43 UTC by ldecarvalho-doc

### Your checklist for this pull request

- [ ] Check that the commit messages match our requested structure.
- [ ] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).

### Description
Please describe your pull request.

2022-07-29 13:57 UTC, ofranc approved these changes

2022-07-29 15:15 UTC, nzerhouni requested changes

2022-07-29 15:15 UTC, nzerhouni commented on managed-databases/postgresql-and-mysql/how-to/manage-permissions.mdx
>    paragraph: This page explains how to manage user permissions on a Database
```suggestion
  paragraph: This page explains how to manage user permissions on a Database Instance
```

2022-08-01 08:21 UTC, nedaehm approved these changes

2022-08-01 08:22 UTC, merged