feat(messaging): added go doc
scaleway/docs-content pull request #878
Opened 2022-09-22 12:34 UTC by RoRoJ

### Your checklist for this pull request

- [x] Check that the commit messages match our requested structure.
- [x] Name your pull request according to the [contribution guidelines](../docs/CONTRIBUTING.md).

### Description
Add Go doc to API/CLI section

2022-09-22 13:54 UTC, albinou requested changes
Looks good. Just a few small comments.

2022-09-22 13:54 UTC, albinou commented on compute/messaging/api-cli/go-sns.mdx
> +```goYour location
```suggestion
```go
```

2022-09-22 13:54 UTC, albinou commented on compute/messaging/api-cli/go-sqs.mdx
> +  The `endpoint_url` for Scaleway Messaging is `http://sqs-sns.mnq.fr-par.scw.cloud`. For the access and secret key values, use the credentials you [generated](/compute/messaging/how-to/create-creden
```suggestion
  The `Endpoint` for Scaleway Messaging is `http://sqs-sns.mnq.fr-par.scw.cloud`. For the access and secret key values, use the credentials you [generated](/compute/messaging/how-to/create-credentials/) for your SNS/SQS namespace.
```

2022-09-23 09:02 UTC, albinou commented
I can't approve, but it looks great now :+1:

2022-09-26 07:19 UTC, ldecarvalho-doc approved these changes

2022-09-26 07:41 UTC, merged